name: Techangel
markdown: redcarpet
pygments: true
permalink: /:categories/:title
baseurl: /techangelsite
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed