---
title: Techangelsite
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  work:
  
name: Techangel
highlighter: rouge
permalink: pretty
excerpt_separator: "<!--more-->"
baseurl: ''
sass:
  sass_dir: _sass
markdown: kramdown
