- title: Pixel Perfect Design
  categories: services
  icons: icon-rocket
  
- title: Retina Display Ready
  categories: services
  icons: icon-dashboard
  
- title: SEO Friendly
  categories: services
  icons: icon-cloud-download
  
- title: Powerful Theme Options
  categories: services
  icons: icon-search